# Site settings
title: Somethings Technical
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A Podcast about many things, some technical.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://somethingstechnical.github.io" # the base hostname & protocol for your site
twitter_username: somethingstechnical
github_username:  somethingstechnical

# Build settings
markdown: kramdown